data:                               # Dataset Configuration
    dataset: "MNIST"
    channel: 1
    batch_size: 32                        # Batch Size
    image_size: 32                        # Image Size

model:                              # Model Configuration
    ch: 32                                # Number of Channels in the Input Feature Map
    out_ch: 1                             # Output Channels
    ch_mult: [1, 2, 4, 8]                 # List of channel numbers per resolution
    num_res_blocks: 3                     # Number of ResNet Blocks per Resolution
    attn_resolutions: [16, ]              # Attention Resolution
    dropout: 0.0                          # Dropout Rate
    in_channels: 1                        # Image Channels
    image_size: 32                        # Image Size
    resamp_with_conv: True                # Resamp with Conv

scheduler: 
    beta_schedule: "cosine_beta_schedule"
    beta_start: 0.0001
    num_diffusion_timestemps: 1000

training:
    epochs: 50
    device: "mps"
    learning_rate: 0.0001